//! Integration tests for schematic parsing and round-trip.
//!
//! Committed fixtures (tests/fixtures/) are generated by this toolchain and
//! run in CI. Real-world schematics from the HQ EDA online viewer demo set
//! are exercised by `#[ignore]`d opt-in tests — see tests/fixtures/README.md.

use kicad_json5::*;
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// HQ EDA demo files (not redistributable). Override with KICAD_DEMO_DIR.
fn hq_demo_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("KICAD_DEMO_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("example_sch")
}

fn load_from(dir: &Path, name: &str) -> String {
    let path = dir.join(name);
    assert!(
        path.exists(),
        "Fixture not found: {} (see tests/fixtures/README.md)",
        path.display()
    );
    std::fs::read_to_string(&path).unwrap()
}

fn parse_sch_from(dir: &Path, name: &str) -> Schematic {
    let source = load_from(dir, name);
    parse_schematic(&source, InputFormat::Sexpr)
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", name, e))
}

fn parse_and_check(name: &str) -> Schematic {
    let schematic = parse_sch_from(&hq_demo_dir(), name);

    assert!(
        !schematic.metadata.uuid.is_empty(),
        "{}: UUID should be non-empty",
        name
    );

    schematic
}

/// Parse → Generate S-expression → Re-parse: the IR should be structurally identical.
fn roundtrip_schematic(name: &str) {
    let original = parse_and_check(name);

    let mut gen = SexprGenerator::new();
    let output = gen.generate(&original).expect("Sexpr generation failed");

    let reparsed =
        parse_schematic(&output, InputFormat::Sexpr).expect("Re-parse of generated output failed");

    assert_eq!(
        original.components.len(),
        reparsed.components.len(),
        "{}: component count mismatch after roundtrip ({} vs {})",
        name,
        original.components.len(),
        reparsed.components.len()
    );

    if !original.wires.is_empty() {
        let wire_ratio = reparsed.wires.len() as f64 / original.wires.len() as f64;
        assert!(
            wire_ratio > 0.5 && wire_ratio < 2.0,
            "{}: wire count diverged too much ({} vs {})",
            name,
            original.wires.len(),
            reparsed.wires.len()
        );
    }

    assert!(
        !original.lib_symbols.is_empty(),
        "{}: should have lib_symbols",
        name
    );
}

// ── Committed fixture: battery-power-board (toolchain-generated) ──

#[test]
fn test_parse_battery_power_board() {
    let sch = parse_sch_from(&fixtures_dir(), "battery-power-board.kicad_sch");
    assert!(!sch.components.is_empty(), "Should have components");
    assert!(!sch.wires.is_empty(), "Should have wires");
    assert!(!sch.lib_symbols.is_empty(), "Should have lib_symbols");
    assert!(!sch.metadata.uuid.is_empty(), "UUID should be non-empty");
}

#[test]
fn test_roundtrip_battery_power_board() {
    let original = parse_sch_from(&fixtures_dir(), "battery-power-board.kicad_sch");

    let mut gen = SexprGenerator::new();
    let output = gen.generate(&original).expect("Sexpr generation failed");

    let reparsed =
        parse_schematic(&output, InputFormat::Sexpr).expect("Re-parse of generated output failed");

    assert_eq!(
        original.components.len(),
        reparsed.components.len(),
        "component count"
    );
    assert_eq!(
        original.lib_symbols.len(),
        reparsed.lib_symbols.len(),
        "lib_symbols count"
    );
}

// ── HQ EDA demo schematics (opt-in, not redistributable) ────
// Run with: KICAD_DEMO_DIR=/path/to/demo cargo test -- --ignored

#[test]
#[ignore = "needs HQ EDA demo fixture Voltage-selection.kicad_sch (see tests/fixtures/README.md)"]
fn test_parse_voltage_selection() {
    let sch = parse_and_check("Voltage-selection.kicad_sch");
    assert!(!sch.components.is_empty(), "Should have components");
    assert!(!sch.wires.is_empty(), "Should have wires");
}

#[test]
#[ignore = "needs HQ EDA demo fixture Voltage-selection.kicad_sch (see tests/fixtures/README.md)"]
fn test_roundtrip_voltage_selection() {
    roundtrip_schematic("Voltage-selection.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture Voltage-selection.kicad_sch (see tests/fixtures/README.md)"]
fn test_topology_voltage_selection() {
    let sch = parse_and_check("Voltage-selection.kicad_sch");
    let summary = kicad_json5::topology::extract_topology(&sch);
    assert!(
        !summary.power_domains.is_empty(),
        "Should detect power domains"
    );
}

#[test]
#[ignore = "needs HQ EDA demo fixture Target-MCU.kicad_sch (see tests/fixtures/README.md)"]
fn test_parse_target_mcu() {
    let sch = parse_and_check("Target-MCU.kicad_sch");
    assert!(
        sch.components.len() > 20,
        "Target-MCU has many components, got {}",
        sch.components.len()
    );
}

#[test]
#[ignore = "needs HQ EDA demo fixture Target-MCU.kicad_sch (see tests/fixtures/README.md)"]
fn test_roundtrip_target_mcu() {
    roundtrip_schematic("Target-MCU.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture USB.kicad_sch (see tests/fixtures/README.md)"]
fn test_parse_usb() {
    let sch = parse_and_check("USB.kicad_sch");
    assert!(
        sch.components.len() > 30,
        "USB has many components, got {}",
        sch.components.len()
    );
}

#[test]
#[ignore = "needs HQ EDA demo fixture USB.kicad_sch (see tests/fixtures/README.md)"]
fn test_roundtrip_usb() {
    roundtrip_schematic("USB.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture WCH-LinkE-R0-1v3.kicad_sch (see tests/fixtures/README.md)"]
fn test_parse_wch_linke() {
    let sch = parse_and_check("WCH-LinkE-R0-1v3.kicad_sch");
    assert!(!sch.components.is_empty());
}

#[test]
#[ignore = "needs HQ EDA demo fixture WCH-LinkE-R0-1v3.kicad_sch (see tests/fixtures/README.md)"]
fn test_roundtrip_wch_linke() {
    roundtrip_schematic("WCH-LinkE-R0-1v3.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture tiny-scarab.kicad_sch (see tests/fixtures/README.md)"]
fn test_parse_tiny_scarab() {
    let sch = parse_and_check("tiny-scarab.kicad_sch");
    assert!(
        sch.components.len() > 50,
        "tiny-scarab should have 50+ components, got {}",
        sch.components.len()
    );
}

#[test]
#[ignore = "needs HQ EDA demo fixture tiny-scarab.kicad_sch (see tests/fixtures/README.md)"]
fn test_roundtrip_tiny_scarab() {
    roundtrip_schematic("tiny-scarab.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture tiny-scarab.kicad_sch (see tests/fixtures/README.md)"]
fn test_topology_tiny_scarab() {
    let sch = parse_and_check("tiny-scarab.kicad_sch");
    let summary = kicad_json5::topology::extract_topology(&sch);
    assert!(
        !summary.power_domains.is_empty(),
        "Should detect power domains"
    );
    assert!(
        !summary.component_summary.by_type.is_empty(),
        "Should have component stats"
    );
}
