//! JSON5 code generator

use crate::error::Result;
use crate::ir::{Net, RenderHint, Schematic, Sheet, Symbol, SymbolInstance};

/// JSON5 generator configuration
#[derive(Debug, Clone)]
pub struct Json5Config {
    /// Indentation string (e.g., "  " or "    ")
    pub indent: String,
    /// Include comments in output
    pub comments: bool,
    /// Include empty fields
    pub include_empty: bool,
}

impl Default for Json5Config {
    fn default() -> Self {
        Self {
            indent: "  ".to_string(),
            comments: true,
            include_empty: false,
        }
    }
}

/// JSON5 generator
pub struct Json5Generator {
    config: Json5Config,
    #[allow(dead_code)]
    indent_level: usize,
}

impl Json5Generator {
    /// Create a new generator with default config
    pub fn new() -> Self {
        Self {
            config: Json5Config::default(),
            indent_level: 0,
        }
    }

    /// Create a generator with custom config
    pub fn with_config(config: Json5Config) -> Self {
        Self {
            config,
            indent_level: 0,
        }
    }

    /// Generate JSON5 from schematic
    pub fn generate(&self, schematic: &Schematic) -> Result<String> {
        let mut output = String::new();

        // Schema comment
        if self.config.comments {
            output.push_str("// KiCad Schematic in JSON5 format\n");
            output.push_str("// Generated by kicad-json5 compiler\n\n");
        }

        output.push_str("{\n");

        // Version and generator
        self.write_field(&mut output, "version", &format!("\"{}\"", schematic.metadata.version), 1);
        self.write_field(&mut output, "generator", &format!("\"{}\"", schematic.metadata.generator), 1);
        if let Some(ref gv) = schematic.metadata.generator_version {
            self.write_field(&mut output, "generator_version", &format!("\"{}\"", gv), 1);
        }

        output.push_str("\n");

        // Metadata
        self.write_metadata(&mut output, schematic);

        // Library symbols
        if !schematic.lib_symbols.is_empty() || self.config.include_empty {
            self.write_lib_symbols(&mut output, schematic);
        }

        // Nets
        if !schematic.nets.is_empty() || self.config.include_empty {
            self.write_nets(&mut output, schematic);
        }

        // Components
        if !schematic.components.is_empty() || self.config.include_empty {
            self.write_components(&mut output, schematic);
        }

        // Wires
        if !schematic.wires.is_empty() || self.config.include_empty {
            self.write_wires(&mut output, schematic);
        }

        // Labels
        if !schematic.labels.is_empty() || self.config.include_empty {
            self.write_labels(&mut output, schematic);
        }

        // Sheets (hierarchical)
        if !schematic.sheets.is_empty() || self.config.include_empty {
            self.write_sheets(&mut output, schematic);
        }

        // Junctions
        if !schematic.junctions.is_empty() || self.config.include_empty {
            self.write_junctions(&mut output, schematic);
        }

        output.push_str("}\n");

        Ok(output)
    }

    fn indent(&self, level: usize) -> String {
        self.config.indent.repeat(level)
    }

    fn write_field(&self, output: &mut String, name: &str, value: &str, indent_level: usize) {
        output.push_str(&format!("{}{}: {},\n", self.indent(indent_level), name, value));
    }

    fn write_field_no_comma(&self, output: &mut String, name: &str, value: &str, indent_level: usize) {
        output.push_str(&format!("{}{}: {}\n", self.indent(indent_level), name, value));
    }

    fn write_metadata(&self, output: &mut String, schematic: &Schematic) {
        output.push_str(&format!("{}metadata: {{\n", self.indent(1)));

        if self.config.comments {
            output.push_str(&format!("{}// Document identification\n", self.indent(2)));
        }

        let tb = &schematic.metadata.title_block;
        let paper = &schematic.metadata.paper;

        self.write_field(output, "uuid", &format!("\"{}\"", schematic.metadata.uuid), 2);

        if let Some(title) = &tb.title {
            self.write_field(output, "title", &format!("\"{}\"", self.escape_string(title)), 2);
        }
        if let Some(date) = &tb.date {
            self.write_field(output, "date", &format!("\"{}\"", date), 2);
        }
        if let Some(rev) = &tb.rev {
            self.write_field(output, "rev", &format!("\"{}\"", rev), 2);
        }
        if let Some(company) = &tb.company {
            self.write_field(output, "company", &format!("\"{}\"", self.escape_string(company)), 2);
        }

        self.write_field(output, "paper", &format!("\"{}\"", paper.size), 2);

        // Comments
        if !tb.comments.is_empty() {
            output.push_str(&format!("{}comments: [\n", self.indent(2)));
            for comment in &tb.comments {
                output.push_str(&format!("{}\"{}\",\n", self.indent(3), self.escape_string(comment)));
            }
            output.push_str(&format!("{}],\n", self.indent(2)));
        }

        output.push_str(&format!("{}}},\n\n", self.indent(1)));
    }

    fn write_lib_symbols(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Library symbols definitions\n", self.indent(1)));
        }

        output.push_str(&format!("{}lib_symbols: [\n", self.indent(1)));

        for symbol in &schematic.lib_symbols {
            self.write_symbol(output, symbol);
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_symbol(&self, output: &mut String, symbol: &Symbol) {
        output.push_str(&format!("{}{{\n", self.indent(2)));
        self.write_field(output, "id", &format!("\"{}\"", symbol.lib_id), 3);

        if !symbol.reference.is_empty() {
            self.write_field(output, "reference", &format!("\"{}\"", symbol.reference), 3);
        }

        if symbol.pin_numbers_hidden {
            self.write_field(output, "pin_numbers", "\"hide\"", 3);
        }

        if symbol.is_power {
            self.write_field(output, "power", "true", 3);
        }

        self.write_field(output, "in_bom", &symbol.in_bom.to_string(), 3);
        self.write_field(output, "on_board", &symbol.on_board.to_string(), 3);
        self.write_field(output, "exclude_from_sim", &symbol.exclude_from_sim.to_string(), 3);
        self.write_field(output, "in_pos_files", &symbol.in_pos_files.to_string(), 3);
        self.write_field(output, "duplicate_pin_numbers_are_jumpers", &symbol.duplicate_pin_numbers_are_jumpers.to_string(), 3);

        // Properties
        if !symbol.properties.is_empty() {
            output.push_str(&format!("{}properties: {{\n", self.indent(3)));
            for prop in &symbol.properties {
                output.push_str(&format!("{}\"{}\": \"{}\",\n",
                    self.indent(4),
                    self.escape_string(&prop.name),
                    self.escape_string(&prop.value)
                ));
            }
            output.push_str(&format!("{}}},\n", self.indent(3)));
        }

        // Pins
        if !symbol.pins.is_empty() {
            output.push_str(&format!("{}pins: [\n", self.indent(3)));
            for pin in &symbol.pins {
                output.push_str(&format!("{}{{ number: \"{}\", name: \"{}\", type: \"{}\" }},\n",
                    self.indent(4),
                    pin.number,
                    self.escape_string(&pin.name),
                    pin.pin_type
                ));
            }
            output.push_str(&format!("{}],\n", self.indent(3)));
        }

        output.push_str(&format!("{}}},\n", self.indent(2)));
    }

    fn write_nets(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Net definitions\n", self.indent(1)));
        }

        output.push_str(&format!("{}nets: [\n", self.indent(1)));

        for net in &schematic.nets {
            self.write_net(output, net);
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_net(&self, output: &mut String, net: &Net) {
        output.push_str(&format!("{}{{\n", self.indent(2)));
        self.write_field(output, "id", &net.id.to_string(), 3);
        self.write_field(output, "name", &format!("\"{}\"", self.escape_string(&net.name)), 3);

        if let Some(net_type) = &net.net_type {
            self.write_field(output, "type", &format!("\"{}\"", net_type), 3);
        }

        if net.render != RenderHint::default() {
            self.write_field(output, "render", &format!("\"{}\"", net.render.as_str()), 3);
        }

        output.push_str(&format!("{}}},\n", self.indent(2)));
    }

    fn write_components(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Component instances\n", self.indent(1)));
        }

        output.push_str(&format!("{}components: [\n", self.indent(1)));

        for component in &schematic.components {
            self.write_component(output, component);
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_component(&self, output: &mut String, component: &SymbolInstance) {
        output.push_str(&format!("{}{{\n", self.indent(2)));

        self.write_field(output, "ref", &format!("\"{}\"", component.reference), 3);
        self.write_field(output, "lib_id", &format!("\"{}\"", component.lib_id), 3);
        self.write_field(output, "value", &format!("\"{}\"", self.escape_string(&component.value)), 3);

        if let Some(footprint) = &component.footprint {
            self.write_field(output, "footprint", &format!("\"{}\"", footprint), 3);
        }

        // Position
        output.push_str(&format!("{}position: {{\n", self.indent(3)));
        self.write_field(output, "x", &component.position.0.to_string(), 4);
        self.write_field(output, "y", &component.position.1.to_string(), 4);
        self.write_field_no_comma(output, "rotation", &component.position.2.to_string(), 4);
        output.push_str(&format!("{}}},\n", self.indent(3)));

        // Mirror
        let mirror_str = match component.mirror {
            crate::ir::Mirror::None => "none",
            crate::ir::Mirror::X => "x",
            crate::ir::Mirror::Y => "y",
        };
        if component.mirror != crate::ir::Mirror::None {
            self.write_field(output, "mirror", &format!("\"{}\"", mirror_str), 3);
        }

        // UUID
        if let Some(uuid) = &component.uuid {
            self.write_field(output, "uuid", &format!("\"{}\"", uuid), 3);
        }

        // Unit
        self.write_field(output, "unit", &component.unit.to_string(), 3);

        // KiCad 8+ flags
        self.write_field(output, "exclude_from_sim", &component.exclude_from_sim.to_string(), 3);
        self.write_field(output, "in_bom", &component.in_bom.to_string(), 3);
        self.write_field(output, "on_board", &component.on_board.to_string(), 3);
        self.write_field(output, "dnp", &component.dnp.to_string(), 3);

        // Instances
        if !component.instances.projects.is_empty() {
            output.push_str(&format!("{}instances: [\n", self.indent(3)));
            for project in &component.instances.projects {
                output.push_str(&format!("{}{{\n", self.indent(4)));
                self.write_field(output, "project", &format!("\"{}\"", self.escape_string(&project.name)), 5);
                output.push_str(&format!("{}paths: [\n", self.indent(5)));
                for path in &project.paths {
                    output.push_str(&format!("{}{{\n", self.indent(6)));
                    self.write_field(output, "path", &format!("\"{}\"", path.path), 7);
                    self.write_field(output, "reference", &format!("\"{}\"", self.escape_string(&path.reference)), 7);
                    self.write_field_no_comma(output, "unit", &path.unit.to_string(), 7);
                    output.push_str(&format!("{}}},\n", self.indent(6)));
                }
                output.push_str(&format!("{}],\n", self.indent(5)));
                output.push_str(&format!("{}}},\n", self.indent(4)));
            }
            output.push_str(&format!("{}],\n", self.indent(3)));
        }

        // Properties
        if !component.properties.is_empty() {
            output.push_str(&format!("{}properties: {{\n", self.indent(3)));
            for (key, value) in &component.properties {
                output.push_str(&format!("{}\"{}\": \"{}\",\n",
                    self.indent(4),
                    self.escape_string(key),
                    self.escape_string(value)
                ));
            }
            output.push_str(&format!("{}}},\n", self.indent(3)));
        }

        // Pins
        if !component.pins.is_empty() {
            output.push_str(&format!("{}pins: {{\n", self.indent(3)));
            for pin in &component.pins {
                output.push_str(&format!("{}\"{}\": {{\n", self.indent(4), pin.number));
                if !pin.name.is_empty() {
                    self.write_field(output, "name", &format!("\"{}\"", self.escape_string(&pin.name)), 5);
                }
                if let Some(net_id) = pin.net_id {
                    self.write_field(output, "net", &net_id.to_string(), 5);
                    if let Some(net_name) = &pin.net_name {
                        self.write_field(output, "net_name", &format!("\"{}\"", net_name), 5);
                    }
                }
                output.push_str(&format!("{}}},\n", self.indent(4)));
            }
            output.push_str(&format!("{}}},\n", self.indent(3)));
        }

        output.push_str(&format!("{}}},\n", self.indent(2)));
    }

    fn write_wires(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Wire segments\n", self.indent(1)));
        }

        output.push_str(&format!("{}wires: [\n", self.indent(1)));

        for wire in &schematic.wires {
            output.push_str(&format!("{}{{\n", self.indent(2)));
            output.push_str(&format!("{}start: [{}, {}],\n", self.indent(3), wire.start.0, wire.start.1));
            output.push_str(&format!("{}end: [{}, {}],\n", self.indent(3), wire.end.0, wire.end.1));

            if let Some(net_id) = wire.net_id {
                self.write_field(output, "net", &net_id.to_string(), 3);
            }

            output.push_str(&format!("{}stroke: {{ width: {}, type: \"{}\" }},\n",
                self.indent(3),
                wire.stroke.width,
                wire.stroke.stroke_type
            ));

            output.push_str(&format!("{}}},\n", self.indent(2)));
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_labels(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Labels\n", self.indent(1)));
        }

        output.push_str(&format!("{}labels: [\n", self.indent(1)));

        for label in &schematic.labels {
            output.push_str(&format!("{}{{\n", self.indent(2)));
            self.write_field(output, "text", &format!("\"{}\"", self.escape_string(&label.text)), 3);
            self.write_field(output, "type", &format!("\"{}\"", label.label_type), 3);

            output.push_str(&format!("{}position: {{\n", self.indent(3)));
            self.write_field(output, "x", &label.position.0.to_string(), 4);
            self.write_field(output, "y", &label.position.1.to_string(), 4);
            self.write_field_no_comma(output, "rotation", &label.position.2.to_string(), 4);
            output.push_str(&format!("{}}},\n", self.indent(3)));

            output.push_str(&format!("{}}},\n", self.indent(2)));
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_junctions(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Junction points\n", self.indent(1)));
        }

        output.push_str(&format!("{}junctions: [\n", self.indent(1)));

        for junction in &schematic.junctions {
            output.push_str(&format!("{}{{ position: [{}, {}], diameter: {} }},\n",
                self.indent(2),
                junction.position.0,
                junction.position.1,
                junction.diameter
            ));
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_sheets(&self, output: &mut String, schematic: &Schematic) {
        if self.config.comments {
            output.push_str(&format!("{}// Hierarchical sheets\n", self.indent(1)));
        }

        output.push_str(&format!("{}sheets: [\n", self.indent(1)));

        for sheet in &schematic.sheets {
            self.write_sheet(output, sheet);
        }

        output.push_str(&format!("{}],\n\n", self.indent(1)));
    }

    fn write_sheet(&self, output: &mut String, sheet: &Sheet) {
        output.push_str(&format!("{}{{\n", self.indent(2)));
        self.write_field(output, "sheet_name", &format!("\"{}\"", self.escape_string(&sheet.sheet_name.value)), 3);
        self.write_field(output, "sheet_file", &format!("\"{}\"", self.escape_string(&sheet.sheet_file.value)), 3);
        output.push_str(&format!("{}position: [{}, {}],\n", self.indent(3), sheet.position.0, sheet.position.1));
        output.push_str(&format!("{}size: [{}, {}],\n", self.indent(3), sheet.size.0, sheet.size.1));

        if !sheet.pins.is_empty() {
            output.push_str(&format!("{}pins: [\n", self.indent(3)));
            for pin in &sheet.pins {
                output.push_str(&format!("{}{{ name: \"{}\", type: \"{}\" }},\n",
                    self.indent(4),
                    self.escape_string(&pin.name),
                    pin.pin_type.to_str()
                ));
            }
            output.push_str(&format!("{}],\n", self.indent(3)));
        }

        output.push_str(&format!("{}}},\n", self.indent(2)));
    }

    /// Escape special characters in a string
    fn escape_string(&self, s: &str) -> String {
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t")
    }
}

impl Default for Json5Generator {
    fn default() -> Self {
        Self::new()
    }
}
