use anyhow::Result;
use std::path::Path;

/// Generate a lib-table file content (sym_lib_table or fp_lib_table)
pub fn generate_lib_table(table_name: &str, libs: &[(String, String)]) -> String {
    let mut s = String::new();
    s.push_str(&format!("({} (version 7)\n", table_name));
    for (name, uri) in libs {
        s.push_str(&format!(
            "  (lib (name \"{}\")(type \"KiCad\")(uri \"{}\")(options \"\")(descr \"Generated by kicad-symgen\"))\n",
            name, uri
        ));
    }
    s.push_str(")\n");
    s
}

/// Scan a directory and collect .kicad_sym library entries
pub fn scan_sym_libraries(dir: &Path) -> Result<Vec<(String, String)>> {
    let mut libs = Vec::new();
    if !dir.exists() {
        return Ok(libs);
    }

    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if let Some(ext) = path.extension() {
            if ext == "kicad_sym" {
                let name = path.file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("unknown")
                    .to_string();
                let uri = format!("${{KIPRJDIR}}/{}", path.strip_prefix(dir)
                    .unwrap_or(&path)
                    .to_str()
                    .unwrap_or(""));
                libs.push((name, uri));
            }
        }
    }

    libs.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(libs)
}

/// Scan a directory and collect footprint library entries (.pretty dirs)
pub fn scan_fp_libraries(dir: &Path) -> Result<Vec<(String, String)>> {
    let mut libs = Vec::new();
    if !dir.exists() {
        return Ok(libs);
    }

    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            if let Some(name) = path.file_name().and_then(|s| s.to_str()) {
                if name.ends_with(".pretty") {
                    let lib_name = name.trim_end_matches(".pretty").to_string();
                    let uri = format!("${{KIPRJDIR}}/{}", name);
                    libs.push((lib_name, uri));
                }
            }
        }
    }

    if libs.is_empty() {
        let name = dir.file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("footprints")
            .to_string();
        libs.push((name, format!("${{KIPRJDIR}}/{}", dir.display())));
    }

    libs.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(libs)
}
