//! Integration test: render real .kicad_sch files to SVG.
//!
//! Committed fixtures (tests/fixtures/) are generated by the toolchain and
//! run in CI. Real-world schematics from the HQ EDA online viewer demo set
//! (via ecad-viewer) are exercised by `#[ignore]`d opt-in tests —
//! see tests/fixtures/README.md.

use kicad_json5::{Lexer, Parser};
use kicad_render::render_core::Matrix;
use kicad_render::renderer::Renderer;
use kicad_render::renderer::SvgRenderer;
use kicad_render::schematic_renderer::SchematicRenderer;
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// HQ EDA demo files (not redistributable). Override with KICAD_DEMO_DIR.
fn hq_demo_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("KICAD_DEMO_DIR") {
        return PathBuf::from(dir);
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("example_sch")
}

fn render_schematic(schematic: &kicad_json5::Schematic, name: &str) -> String {
    let sch_renderer = SchematicRenderer::new(schematic).with_file_name(name.to_string());
    let bbox = sch_renderer.bbox();
    let (paper_w, paper_h) = sch_renderer.paper_size();

    assert!(paper_w > 0.0, "{}: paper width should be positive", name);
    assert!(paper_h > 0.0, "{}: paper height should be positive", name);
    assert!(
        !bbox.is_empty(),
        "{}: bounding box should not be empty",
        name
    );

    let scale = 3.0;
    let scale_matrix = Matrix::new([scale, 0.0, 0.0, scale, 0.0, 0.0]);
    let mut svg_renderer = SvgRenderer::new();
    svg_renderer.set_transform(&scale_matrix);
    sch_renderer.render(&mut svg_renderer);

    let output = svg_renderer.output();
    assert!(
        !output.is_empty(),
        "{}: SVG output should not be empty",
        name
    );
    assert!(
        output.contains("<circle") || output.contains("<polyline") || output.contains("<text"),
        "{}: SVG should contain graphical elements",
        name
    );

    output
}

fn render_file_from(dir: &Path, name: &str) -> String {
    let path = dir.join(name);
    assert!(
        path.exists(),
        "Fixture not found: {} (see tests/fixtures/README.md)",
        path.display()
    );
    let source = std::fs::read_to_string(&path).unwrap();

    let lexer = Lexer::new(&source);
    let mut parser = Parser::new(lexer);
    let schematic = parser
        .parse()
        .unwrap_or_else(|e| panic!("Failed to parse {}: {}", name, e));
    render_schematic(&schematic, name)
}

// ── Committed fixture: battery-power-board (toolchain-generated) ──

#[test]
fn test_render_battery_power_board() {
    render_file_from(&fixtures_dir(), "battery-power-board.kicad_sch");
}

// JSON5 → auto-layout → render, entirely in-process: this used to depend on
// a file written into a shared directory by kicad-json5's own test run.
#[test]
fn test_render_auto_layout_board() {
    let json5_path = fixtures_dir().join("battery-power-board-auto-layout.json5");
    let json5 = std::fs::read_to_string(&json5_path).expect("fixture json5 not found");

    let mut sch = kicad_json5::parse_json5(&json5).expect("Failed to parse JSON5");
    kicad_json5::layout::apply_to(&mut sch);

    let svg_content = render_schematic(&sch, "battery-power-board-auto.kicad_sch");
    let svg_doc = format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"891\" height=\"630\" viewBox=\"0 0 891 630\">\n{}\n</svg>",
        svg_content
    );
    let out_path = std::env::temp_dir().join("battery-power-board-auto-test.svg");
    std::fs::write(&out_path, &svg_doc).unwrap();
}

// ── HQ EDA demo schematics (opt-in, not redistributable) ────
// Run with: KICAD_DEMO_DIR=/path/to/demo cargo test -- --ignored

#[test]
#[ignore = "needs HQ EDA demo fixture Voltage-selection.kicad_sch (see tests/fixtures/README.md)"]
fn test_render_voltage_selection() {
    render_file_from(&hq_demo_dir(), "Voltage-selection.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture Target-MCU.kicad_sch (see tests/fixtures/README.md)"]
fn test_render_target_mcu() {
    render_file_from(&hq_demo_dir(), "Target-MCU.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture USB.kicad_sch (see tests/fixtures/README.md)"]
fn test_render_usb() {
    render_file_from(&hq_demo_dir(), "USB.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture WCH-LinkE-R0-1v3.kicad_sch (see tests/fixtures/README.md)"]
fn test_render_wch_linke() {
    render_file_from(&hq_demo_dir(), "WCH-LinkE-R0-1v3.kicad_sch");
}

#[test]
#[ignore = "needs HQ EDA demo fixture tiny-scarab.kicad_sch (see tests/fixtures/README.md)"]
fn test_render_tiny_scarab() {
    render_file_from(&hq_demo_dir(), "tiny-scarab.kicad_sch");
}
