//! PCB rendering pipeline: parse → render, and board JSON5 round-trip.
//! Runs on a committed fixture (generated by this toolchain) and writes
//! inspection artifacts to the system temp dir.

use std::path::PathBuf;

use kicad_json5::codegen::BoardSexprGenerator;
use kicad_json5::generate_board_json5;
use kicad_json5::ir::board::Board;
use kicad_json5::parse_board;
use kicad_json5::parse_board_json5;
use kicad_render::pcb_renderer::PcbRenderer;

fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/battery-power-board.kicad_pcb")
}

fn load_board() -> Board {
    let source = std::fs::read_to_string(fixture()).expect("fixture board not found");
    parse_board(&source).expect("Failed to parse .kicad_pcb")
}

#[test]
fn render_fixture_pcb() {
    let board = load_board();

    assert!(!board.footprints.is_empty(), "should have footprints");
    assert!(!board.segments.is_empty(), "should have segments");
    assert!(!board.zones.is_empty(), "should have zones");
    assert!(!board.graphics.is_empty(), "should have board graphics");

    let renderer = PcbRenderer::new(&board).with_dpi(150.0);
    let svg = renderer.render_to_string();
    assert!(svg.contains("<svg"), "SVG output must be a document");
    assert!(svg.len() > 10_000, "rendered board should be substantive");

    let out = std::env::temp_dir().join("cdb-fixture-board.svg");
    std::fs::write(&out, &svg).unwrap();
}

#[test]
fn board_json5_roundtrip() {
    let board = load_board();
    let fp_count = board.footprints.len();
    let seg_count = board.segments.len();
    let via_count = board.vias.len();
    let zone_count = board.zones.len();
    let net_count = board.nets.len();
    let gr_count = board.graphics.len();

    // Board IR → JSON5 → Board IR
    let json5 = generate_board_json5(&board).expect("generate Board JSON5");
    let board2 = parse_board_json5(&json5).expect("parse Board JSON5");

    assert_eq!(board2.footprints.len(), fp_count, "footprint count");
    assert_eq!(board2.segments.len(), seg_count, "segment count");
    assert_eq!(board2.vias.len(), via_count, "via count");
    assert_eq!(board2.zones.len(), zone_count, "zone count");
    assert_eq!(board2.nets.len(), net_count, "net count");
    assert_eq!(board2.graphics.len(), gr_count, "graphics count");

    for (i, (n1, n2)) in board.nets.iter().zip(board2.nets.iter()).enumerate() {
        assert_eq!(n1.name, n2.name, "net {} name mismatch", i);
        assert_eq!(n1.id, n2.id, "net {} id mismatch", i);
    }
    for (i, (fp1, fp2)) in board
        .footprints
        .iter()
        .zip(board2.footprints.iter())
        .enumerate()
    {
        assert_eq!(fp1.reference, fp2.reference, "fp {} ref mismatch", i);
        assert_eq!(fp1.value, fp2.value, "fp {} value mismatch", i);
        assert_eq!(fp1.lib_id, fp2.lib_id, "fp {} lib_id mismatch", i);
    }

    // Round-tripped board renders
    let renderer = PcbRenderer::new(&board2).with_scale(3.0);
    let svg = renderer.render_to_string();
    assert!(svg.contains("<svg"));

    let out = std::env::temp_dir().join("cdb-fixture-board-rt.svg");
    std::fs::write(&out, &svg).unwrap();
}

// Round-trip through the canonical S-expression form too.
#[test]
fn board_sexpr_roundtrip() {
    let board = load_board();
    let mut gen = BoardSexprGenerator::new();
    let sexpr = gen.generate(&board).expect("sexpr generate");
    let board2 = parse_board(&sexpr).expect("re-parse");

    assert_eq!(
        board2.footprints.len(),
        board.footprints.len(),
        "footprints"
    );
    assert_eq!(board2.segments.len(), board.segments.len(), "segments");
    assert_eq!(board2.zones.len(), board.zones.len(), "zones");
    assert_eq!(board2.graphics.len(), board.graphics.len(), "graphics");
}
